### ISSUE TITLE
HTTPS problem

### ISSUE THREAD

**Issue by f3l1x** [juniwalk/juniwalk.cz#1]
![image](https://cloud.githubusercontent.com/assets/538058/14232110/aa3fb14a-f99d-11e5-9f9d-6490f257f682.png)

**Comment by juniwalk** [comment]
Renewnul jsem cert po tom co jsem se na to vykašlal, ale měl jsem tam zaplé HPKP což je něco s čím né tak úplně umím a stránka mi nejde ve FF.

Každopádně zkus to :)
